# Generated by Django 2.1.7 on 2019-12-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusionapp', '0002_auto_20191222_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='month',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
